# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
# 
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.


main:
  - name: "News"
    pageRef: "posts"
    weight: 10

  - name: "Research"
    weight: 20

  - name: "Themes"
    parent: "Research"
    pageRef: "research"
    weight: 10

  - name: "Projects"
    parent: "Research"
    pageRef: "projects"
    weight: 20

  - name: "Members"
    pageRef: "team"
    weight: 25

  - name: "Contact"
    pageRef: "contact"
    weight: 50

#  - name: "Categories"
#    pageRef: "categories"
#    weight: 20

#  - name: "Tags"
#    pageRef: "tags"
#    weight: 30

subnavigation:
  - name: "*Publications*"
    pageRef: "publications"
    weight: 30

  - name: "*Himeno Benchmark*"
    pageRef: "himeno_benchmark"
    weight: 40

  - pre: "github"
    url: "https://github.com/himeno-sun-lab/"
    weight: 99


# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.



# footer:
#   - name: "Tags"
#     pageRef: "tags"
#     weight: 10

#   - name: "Categories"
#     pageRef: "categories"
#     weight: 20